

POST https://expenses-tracker-backend-1-0b6w.onrender.com/createuser
Content-Type:application/json

{
    "name":"sasuke uchiha",
    "email":"sasuke@gmail.com",
    "password":"123456",
    "profileImage":"https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=300"
}

###

POST https://expenses-tracker-backend-1-0b6w.onrender.com/user
Content-Type:application/json 

{
    "email":"sasuke@gmail.com",
    "password":"123456"
}

###

GET https://expenses-tracker-backend-1-0b6w.onrender.com/transaction
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTNhYWFiZjRkM2RiY2EwYTI2ZTY2NWQiLCJpYXQiOjE3ODIyMzA3OTYsImV4cCI6MTc4NDgyMjc5Nn0.myopm6jVvZGlXSro8VpvE49T3bWCE_-6PwbiQR2RNK4

###
GET https://expenses-tracker-backend-1-0b6w.onrender.com/gettransaction

###

POST https://expenses-tracker-backend-1-0b6w.onrender.com/addtransaction
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTNhYWFiZjRkM2RiY2EwYTI2ZTY2NWQiLCJpYXQiOjE3ODIyMzA3OTYsImV4cCI6MTc4NDgyMjc5Nn0.myopm6jVvZGlXSro8VpvE49T3bWCE_-6PwbiQR2RNK4

{
    "description":"Biriyani",
    "amount":600,
    "category":"Food",
    "paymentMethod":"Cash",
    "date":"2026-06-20",
    "type":"Expenses"
}

###

DELETE https://expenses-tracker-backend-1-0b6w.onrender.com/deleteall

###

PUT https://expenses-tracker-backend-1-0b6w.onrender.com/updatetransaction

###

DELETE https://expenses-tracker-backend-1-0b6w.onrender.com/deletetransaction

###